@startmindmap
toleft p to right direction

*:==IPBES
----
;
**:==Assessment
----
  **XYZ** three letter assesment abbreviation
;

***:==SPM
----
  **Language**
;
****:=Document
;
****:=Figure
----
  **Figure x.y**
;
*****:=Data Management Report
----
;
******:=Data
----
;
******:=Technical Document
----
;
****:=Table
----
  **Table x.y**
;
*****:=Data Management Report
----
;
******:=Data
----
;
******:=Technical Document
----
;
****:=Data Management Report
----
;
*****:=Data
----
;
*****:=Technical Document
----
;

***:=Chapter
----
  **Chapter x**
;

****:=Document
----
;

****:=Figure
----
  **Figure x.y**
;
*****:=Data Management Report
----
;
******:=Data
----
;
******:=Technical Document
----
;
****:=Table
----
  **Table x.y**
;
*****:=Data Management Report
----
;
******:=Data
----
;
******:=Technical Document
----
;
****:=Data Management Report
----
;
*****:=Data
----
;
*****:=Technical Document
----
;
****:=Glossary
----
;
****:=Bibliography
----
;
**:=Decision
----
;
@endmindmap